name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "petweight" #Must be unique in Heroku
          heroku_email: "midowahdan11@gmail.com"
          usedocker: true
          docker_build_args: |
            NODE_ENV
            DB_URL
        env:
          NODE_ENV: production
          DB_URL: ${{ secrets.DB_URL }}
